"""empty message

Revision ID: 4c55cdd72977
Revises: 
Create Date: 2017-02-16 22:21:31.912544

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '4c55cdd72977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('nickname',sa.String(255),nullable=True),
    sa.Column('create_time',sa.DateTime(),default=datetime.now),
    sa.Column('update_time',sa.DateTime(),onupdate=datetime.now),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
